version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/aspnet:6.0 
    steps:
      - checkout 
      - run:
          name: Restore dependencies
          command: dotnet restore  
      - run:
          name: Build the project
          command: dotnet build  
      - run:
          name: Run unit tests
          command: dotnet test --no-build 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build 
